version: "3.7"

services:
  webserver:
    image: nginx
    volumes:
      - ./dev/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: img_lookup
      POSTGRES_PASSWORD: img_lookup
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
  frontend:
    command: yarn dev --host
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
  backend:
    command: python3 manage.py runserver 0.0.0.0:8000
    build:
      context: backend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/:/app/
    env_file:
      - .env
    depends_on:
      - database
      - storage
      - redis
  backend_worker:
    command: python3 manage.py qcluster
    build:
      context: backend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/:/app/
      - ./dev/secrets/google-service-account.json:/app/google-service-account.json
    env_file:
      - .env
    depends_on:
      - database
      - storage
      - redis
  storage:
    image: bitnami/minio
    volumes:
      - storage-data:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: "DevelopmentAccessKey"
      MINIO_ROOT_PASSWORD: "DevelopmentSecretKey"
      MINIO_DEFAULT_BUCKETS: img-lookup
    ports:
      - "9000:9000"
      - "9001:9001"
  redis:
    image: redis:latest

volumes:
  postgres-data:
  storage-data:
