FROM python:3.11.6-slim-bullseye

WORKDIR /app/src

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

COPY . /app
COPY requirements.txt /tmp/requirements.txt

RUN pip3 install -r /tmp/requirements.txt
RUN pip3 install gunicorn

EXPOSE 8000