# Generated by Django 5.0 on 2023-12-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='content_type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
