# Generated by Django 5.0 on 2023-12-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_asset_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
