# Generated by Django 5.0 on 2023-12-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_asset_is_available'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(models.F('file_key'), name='unique_file_key'),
        ),
        migrations.AddConstraint(
            model_name='assetinspection',
            constraint=models.UniqueConstraint(models.F('asset'), models.F('inspection_type'), name='unique_asset_inspection_type'),
        ),
    ]
