# Generated by Django 5.0 on 2024-01-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_asset_unique_file_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assetinspection',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='app.asset'),
        ),
        migrations.AlterField(
            model_name='assetinspection',
            name='inspection_type',
            field=models.TextField(choices=[('vision', 'Vision'), ('metadata', 'Metadata'), ('place', 'Place')]),
        ),
    ]
