# Generated by Django 5.0 on 2024-01-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_asset_height_asset_width_alter_assetinspection_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='orientation_diff',
            field=models.BooleanField(default=False),
        ),
    ]
