# Generated by Django 5.0 on 2024-01-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_asset_orientation_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
    ]
